source 'https://rubygems.org'

# Jekyll
gem "jekyll", "2.4.0"
gem "jekyll-coffeescript", "1.0.1"
gem "jekyll-sass-converter", "1.2.0"

# Converters
gem "kramdown", "1.5.0"
gem "maruku", "0.7.0"
gem "rdiscount", "2.1.7"
gem "redcarpet", "3.1.2"
gem "RedCloth", "4.2.9"

# Liquid
gem "liquid", "2.6.1"

# Highlighters
gem "pygments.rb", "0.6.1"

# Plugins
#gem "jemoji"
#gem "jekyll-mentions"
gem "jekyll-redirect-from", "0.6.2"
gem "jekyll-sitemap", "0.6.3"
